const rawMovieList = [
  {
    "version": "1.4",
    "UID": "5b3e094bd083a3497492cf3f",
    "title": "團體預約觀賞第八屆台灣野望國際自然影展",
    "category": "8",
    "showInfo": [
      {
        "time": "2018/09/01 09:00:00",
        "location": "950  臺東縣臺東市59臺東市文化公園路200號",
        "locationName": "卑南遺址公園",
        "onSales": "N",
        "price": "",
        "latitude": "22.792338",
        "longitude": "121.1159849",
        "endTime": "2019/06/30 09:00:00"
      }
    ],
    "showUnit": "台灣野望自然傳播學社、國立臺灣史前文化博物館......等",
    "discountInfo": "",
    "descriptionFilterHtml": "透過英國Wildscreen的協助，台灣野望自然傳播學社自2011年起舉辦「台灣野望國際自然影展」（WildViewTaiwan Film Festival in association with Wildscreen），每年引進台灣20部世界頂尖的生態環境紀錄片，進行為期一年的巡迴播映。野望影展的觀賞重點除了自然生態及環境的相關知識外，更能擴及影片中豐富的創作元素，由畫面音樂以及故事敘述等各種面向欣賞這些結合學術、技術及藝術的頂尖作品。\r\n\r\n卑南遺址公園加入今年度合作行列，於台東進行公開播映，共同推廣自然生態及環境的相關知識。2018年9月1日起至2019年6月30日止，歡迎團體（含學校）預約觀影－－申請團體須購買當日展示廳門票，每次申請限以兩部片為限。\r\n\r\n* 2018年度內，申請者若為中小學學校單位，且搭配「團體預約卑南遺址公園遺址環境教育主題課程」，可由本館提供每校補助一車租車經費（由本館租用），依預約順序至經費用完截止。\r\n\r\n\r\n 影片介紹 \r\n\r\n \r\n\r\n雪虎行動 Operation Snow Tiger     英國 / 60分鐘\r\n\r\n冰天雪地的西伯利亞森林裡，還住著百獸之王－－西伯利亞虎。但這華麗而巨大的獵食者如今面臨了嚴峻的生存危機。主持人暨生物學家麗茲將前往遙遠的北國，與當地科學家一同調查。究竟西伯利亞虎族群還有沒有繁衍壯大的機會？失去母親的三頭幼虎又是否能在酷寒風雪中存活下來？\r\n\r\n製片公司：BBC NHU, BBC Worldwide Limited / Discovery Channel\r\n提名：2014克服萬難獎\r\n\r\n \r\n\r\n \r\n\r\n鯊魚甜心 Shark Girl     澳洲 / 60分鐘\r\n\r\n麥迪遜，一位甜美的澳洲女孩，從小就愛與魚兒們徜徉在美麗的大堡礁海域。當她十四歲時，發現所摯愛的鯊魚數量竟然急遽減少，珊瑚礁生態就要瓦解。麥迪遜決定休學，全心為「家人」挺身而出。她拍攝影片、四處調查、做實驗、演講，麥迪遜竭盡所能，就是要為她親愛的「手足」洗刷兇惡的污名，為牠們的生存權利奮戰到底。\r\n\r\n製片公司：Kaufmann Productions Pty Ltd, In Association with Smithsonian Channel, Terra Mater \u0026 ABC Australia\r\n得獎：2014環境及保育獎\r\n\r\n \r\n\r\n \r\n\r\n地球新荒野：家園 Earth - A New Wild: Home      英國 / 54分鐘\r\n\r\n保育，不再只是在純粹的自然環境下保護野生動物。人類的經濟發展、農業活動和現代社會的演變，讓保育變得更加複雜。四川辛苦在人工環境下飼育瀕危熊貓，小心翼翼訓練才野放。人類需要老虎維持森林生態系運作，卻得面對老虎傷人的問題。當動物和人類活動的界線變得模糊而重疊時，我們需要用更寬濶的視野來建立新時代的自然保育工作。\r\n\r\n製片公司：A Passion Planet and National Geographic Studios Production for PBS\r\n得獎：2016最佳系列獎\r\n\r\n \r\n\r\n \r\n\r\n印度遊獅 India\u0027s Wandering Lions      印度 / 47分鐘\r\n\r\n半世紀前，野生獅子在印度幾乎絕跡，如今牠們回來了！但是，人類和獅子，真的有辦法在同一個區域，相安無事的一起生活嗎？在古吉拉特邦，獅子和人們維持著奇妙且不可思議的關係。人們允許獅群獵食牲畜，而獅子的獵捕和驅趕，讓鹿群不會過度踐踏農地，間接的保護了農作。這套獵食者與社區融合的方法，為我們帶來獨特的保育示範。\r\n\r\n製片公司：Ammonite Films \u0026 Kosmik Global Media\r\n提名：2016最佳創意獎、人與自然獎\r\n\r\n \r\n\r\n \r\n\r\n翠鳥歸來 Returning Kingfisher      荷蘭 / 50分鐘\r\n\r\n拜荷蘭運河上源源不歇的破冰輪所賜，原本在冬季會結冰的河面，因為貨輪往來而不致結冰，意外的提供翠鳥避寒的棲息地，也是難得見到在比較人工環境下所生活的翠鳥影像。翠鳥一家住在小溪邊的土洞裡，一旁鄰著世界上最忙碌的運河。透過高速攝影機，我們得以一窺世界首次拍攝到，地底下從母鳥作巢、產卵到幼雛孵化的全彩紀錄。\r\n\r\n製片公司：Ispida Wildlife Productions BV, co-produced with BNN-VARA\r\n提名：2016最佳新秀獎\r\n\r\n \r\n\r\n \r\n\r\n孤熊重返自然 Life is One      法國 / 52分鐘\r\n\r\n本片主角買下三隻被帶走的月熊寶寶，準備讓牠們習慣森林的野外生活，慢慢重返自然。然而，三隻小熊命運卻大大不同。故事單純圍繞著小熊打轉，透過小熊的視野，葉子、樹枝、森林和蜂巢，一切顯得新鮮有趣。牠們在樹叢裡打滾、絆到枯枝跌倒顯得困惑、興高采烈的爬樹、在陽光下舒服的搔癢，熊與森林的連結多麼美麗而充滿活力。\r\n\r\n製片公司：Tawak Pictures\r\n提名：2016最佳創新獎\r\n\r\n \r\n\r\n \r\n\r\n野地大搜奇 Wild Expectation      美國 / 45分鐘\r\n\r\n巴塔哥尼亞高原有許多神祕、難以目睹其真面目的夢幻生物，藏匿在岩塊與灌叢的高手美洲獅就是其中之一。動物星球的外景主持人，自從偶然見到一隻麒麟尾（尾巴短折）的幼年美洲獅就念念不忘，這次他帶著團隊想再一睹麒麟尾的身影，他們能在蒼蒼野地裡找到美洲獅的蹤跡嗎？在競爭激烈的殘酷野外生活，麒麟尾成功長大了嗎？牠還有可能活著嗎？\r\n\r\n製片公司：Equilibrio Films, LLC in association with Nedo Producciones Ltda. for Animal Planet\r\n提名：2016最佳創新獎、大眾播映獎\r\n\r\n \r\n\r\n \r\n\r\n狂野氣象站：水無常形 Wild Weather with Richard Hammond - Water: The Shape Shifter      英國 / 51分鐘\r\n\r\n天氣，我們習以為常、日日生活都會接觸到的自然現象，竟然藏著令人訝異的力量。就從我們熟悉到不行的「水」來看吧，沒有水就不會有雲、風、雨、雪、冰和霰。主持人用從未有人敢嘗試的瘋狂實驗設計，一一透視各種型態的水：雲有多重？雪有多快？冰的破壞力有多強？天上的雲如果是一團水，掉下來時怎麼不是瀑布，而是細細的雨滴？快意人心的科普實驗，絕對讓人目瞪口呆，強力推薦。\r\n\r\n製片公司：An Oxford Scientific Films/Terra Mater Factual Studios/Open University Co-Production (in association with Hamster’s Wheel and PAAN)\r\n得獎：2016最佳劇本獎\r\n提名：2016最佳系列獎\r\n\r\n \r\n\r\n \r\n\r\n冰山任務 Operation Iceberg      英國 / 60分鐘\r\n\r\n想成為極地探險家嗎？一支結合科學家、攝影師、潛水員與醫生的極地探險隊，在最艱困的極端環境下駐點三週，揭開冰河的神祕面紗。在此之前，從來沒任何探險隊深入冰原，探索冰山的生成與崩落。緊湊的科學調查行動、先進的科學儀器設備，以及純淨的冰原風景，將帶來令人震撼的自然奇觀。\r\n\r\n製片公司：BBC Scotland/BBC Worldwide Co-Production\r\n提名：2014大眾播映獎\r\n\r\n \r\n\r\n\r\n\r\n骨骼之秘：恐龍再現 Attenborough and the Giant Dinosaur      英國 / 60分鐘\r\n\r\n全世界最受歡迎的生物－－恐龍！雖然已經滅絕，但各地人們始終興致勃勃，努力於解開這些生物的謎團。故事從考古學家在阿根廷發現一根巨龍骨頭開始，一路抽絲剝繭：這隻曾是地球上最大生物的恐龍有多大？有多重？吃些什麼？這麼大隻，牠怎麼走路？牠的肌肉和骨頭有什麼特別？牠的蛋跟寶寶長什麼樣子？透過模型重建技術，我們將目睹這雄偉生物的面貌。\r\n\r\n製片公司：BBC, BBC Worldwide \u0026 PBS\r\n入圍：2016最佳科學獎\r\n得獎：2016評審推薦獎\r\n\r\n \r\n\r\n \r\n\r\n復活節彩蛋直播 Easter Eggs Live      英國 / 48分鐘\r\n\r\n你知道地球上的生命有99%是從蛋中誕生的嗎？無論是大蛋、小蛋、素色或帶有斑點的，「蛋」肯定是造物主最精巧的創作之一，也是爬蟲媽媽、兩棲媽媽、魚媽媽、鳥媽媽和昆蟲媽媽的心頭寶貝。讓我們一起跟著主持人馬克伊凡斯和動物專家群，利用高科技的影音掃描設備，一起觀賞一場蛋的實境秀，一窺生命孵化的精彩過程吧！\r\n\r\n製片公司：Windfall Films\r\n提名：2014最佳創新獎\r\n\r\n \r\n\r\n \r\n\r\n獼猴王國 Disneynature Monkey Kingdom      英國 / 81分鐘\r\n\r\n在遙遠的斯里蘭卡森林裡，有一座古老的廢墟，這兒的堡壘石成了猴子生活的樂園。瑪雅是猴家族裡位階較低的母猴，總是被其他猴子欺負和使喚。瑪雅在生下猴寶寶後，她的地位更是搖搖欲墜。有一天，隔壁的猴群攻占了堡壘石，瑪雅的猴家族只能撤退。不過，瑪雅以她的街頭智慧帶領猴群在城鎮間遊走，最後還讓猴群們團結起來，重回堡壘石。瑪雅用她的勇敢和機智，讓猴家族對她刮目相看。\r\n\r\n製片公司：Disneynature, Crazy Ape Productions \u0026 Silverback Films\r\n得獎：2016動物行為獎\r\n\r\n \r\n\r\n\r\n\r\n初踏生命之境 Life Story: First Steps      英國 / 60分鐘\r\n\r\n生命的第一步，在想像中應該是充滿喜悅和感動吧？但多數時候，初生寶寶得在危機四伏的環境中奮力求生。這部影片蒐集從陸地到海洋的許多美妙生物，有的生物採群體戰，兄長手足帶領年幼的認識世界；有的生物靠媽媽的智慧來保護幼兒；還有的靠著自己強大堅毅的信心與勇氣克服萬難。準備好了嗎？一起見識各種幼獸不可思議的求生本領。\r\n\r\n製片公司：BBC, BBC Worldwide, Discovery, France TV \u0026 the Open University\r\n提名：2016最佳系列獎、最佳攝影獎（大型劇組）\r\n\r\n \r\n\r\n \r\n\r\n小象寓言 Naledi: A Baby Elephant\u0027s Tale      美國 / 90分鐘\r\n\r\n感人的象寶寶求生記。位於非洲南部的波札那大象保護區裡，有一頭名為「Naledi」的象寶寶誕生了。「Naledi」的意思是星星，可是，她出生後沒多久就失去了母親，眼見她因不吃不喝而日漸消瘦，保育人員費盡苦心，終於讓她願意進食。但不久之後，Naledi又因為不小心吃下象寶寶還無法消化的植物，需進行緊急手術。Naledi能順利撐過去嗎？非洲其他象群的生活又是如何呢？\r\n\r\n製片公司：Vulcan Productions in association with Off The Fence\r\n提名：2016最佳戲院獎\r\n\r\n \r\n\r\n\r\n\r\n亞馬遜森蚺一族 Tribes, Predators and Me: Anaconda People of the Amazon      英國 / 60分鐘\r\n\r\n森蚺，全世界最大、最重的無毒蟒蛇，就藏在亞馬遜的叢林裡。主持人高登來到地球上最偏遠、與世隔絕的部落，和他們一起生活。這兒的原住民對雨林瞭若指掌，他們帶著高登深入草叢和沼澤尋找森蚺，還自製有毒的吹箭和削尖的長棍去獵猴子和野豬。「奔跑打獵的感覺太熟悉了，幾千年前我們每個人可能都赤腳跑過叢林」進入叢林裡的部落生活，重啟你的自然感官。\r\n\r\n製片公司：BBC \u0026 BBC Worldwide\r\n提名：2016最佳主持人獎\r\n\r\n \r\n\r\n \r\n\r\n滅絕最後關頭 Racing Extinction      美國 / 84分鐘\r\n\r\n地球上已經歷了五次物種大滅絕，如今，恐怕在我們的有生之年上演第六次大滅絕。奧斯卡金獎導演路易賽候尤斯，帶領《血色海灣》幕後團隊，以卧底調查的方式，挑戰危機重重的非法貿易，揭露包括鯊魚、魟魚等多項瀕危物種的地下工廠和祕密黑市。團隊用意想不到的創意行動，把生物的美麗與脆弱，搬進城市的大舞台，投影在高樓上。人們需要知道真相，一起改變！\r\n\r\n製片公司：Okeanos – Foundation for the Sea and Discovery Channel present an Oceanic Preservation Society film. In association with Vulcan Productions, the Li Ka Shing Foundation, Earth Day Texas, JP\u0027s Peace, Love \u0026 Happiness Foundation, Diamond Docs \u0026 Insurgent Docs\r\n提名：2016最佳創新獎、最佳衝擊獎、人與自然獎、最佳播映獎\r\n得獎：2016最佳創新獎、最佳衝擊獎\r\n\r\n \r\n\r\n \r\n\r\n無印野馬 Unbranded      美國 / 106分鐘\r\n\r\n壯濶、史詩般的遠征，4個人與16匹馬，近5000公里的旅行，見證人與馬的真情相伴。這段得耗費五個月才能完成的路線，過去曾是美國西部拓荒者的真實生活，至今仍撩動人心。四個年輕牛仔決定先不急著出社會找工作，而是一起挑戰這個艱鉅任務。他們從德州一路向北，人和馬彼此磨合耐心與脾氣，在原野騎乘的風景非凡，是一部在人物描寫、敘事結構、風景拍攝與配樂等方面都相當純熟的影片。\r\n\r\n製片公司：Fin \u0026 Fur Films LLC, Implement Productions \u0026 Cedar Creek Media LLC\r\n提名：2016最佳戲院獎\r\n\r\n \r\n\r\n \r\n\r\n直擊殺戮現場 Huntwatch      美國 / 88分鐘\r\n\r\n從前，獵海豹被視為一份值得尊敬的工作，人們甚至把獵人當作英雄。但是，當海豹保護團體開始用影像紀錄獵殺海豹的現場，這些畫面很快燃起群眾的怒火。當年輕的行動者布萊恩戴維斯投身海豹保護運動時，他完全不曉得這將是一場終生的戰役。本片紀錄了海豹保衛戰的你來我往，在文化、傳統、經濟收入與物種保育的天平兩端，我們又該採取什麼立場。\r\n\r\n製片公司：IFAW\r\n提名：2016最佳剪輯獎\r\n\r\n \r\n\r\n \r\n\r\n鯨世警示 The Islands and the Whales      英國 / 84分鐘\r\n\r\n遙遠、靠近北極圈的法羅群島，因土地貧瘠常年陰雨，人民仰賴海洋資源維生。鯨魚和海鳥是島民世代以來的糧食，也是他們希望傳承給下一代的生活方式。但是，當地醫生發現廣受喜愛的鯨魚肉有毒，擔憂影響下一代的健康。同時，來自外地的環境運動團體，也以強硬的方式意圖阻擋在地人集體獵殺鯨魚。法羅人該如何在傳統與健康之間做出抉擇？\r\n\r\n製片公司：Intrepid Cinema\r\n提名：2016最佳衝擊獎\r\n\r\n \r\n\r\n \r\n\r\n亞蘇尼人 Yasuni Man      美國 / 93分鐘\r\n\r\n阿凡達真實版！座落在亞馬遜流域，厄瓜多的亞蘇尼區是全世界生物多樣性最豐富的森林，但世代居住在這裡的原住民，卻受到石油公司的開發、盜伐、部族之間的相互殘殺與人權迫害等威脅。導演帶著科學家團隊進駐，發現不為世人所知的繁茂生態祕境。然而，原住民部落之間的戰爭頻傳，原住民與外來石油公司和伐木商的衝突不斷，眼見這塊祕境即將毀於一旦，亞蘇尼人該何去何從？\r\n\r\n製片公司：Pollywog Productions LLC\r\n得獎：2016最佳新秀獎\r\n\r\n\r\n 預約方式 \r\n\r\n滿10人以上即可於活動7日前以電話、Email方式預約觀影。\r\n\r\n\r\n\t電話：(089)233466 #210 李小姐，來電時請告知：\r\n\t　1. 預約日期與時間\r\n\t　2. 參加人數\r\n\t　3. 預約觀賞影片\r\n\t　4. 當日聯絡人資料\r\n\tEmail：請將上述資訊Email至 liyun@nmp.gov.tw，若三日內未收到回覆，請來電確認。\r\n\r\n\r\n\r\n 其他說明 \r\n\r\n\r\n\t播放場地包括特展室、自然教室、多功能教室等，將視各空間使用狀況而定；播放設備為筆電及投影機。\r\n\t各場地可容納人數不等，建議申請團體事先來電與館員溝通，以便安排最合適空間。\r\n\t本場所備有飲水機，請自備環保水杯；為減少垃圾，用餐請備環保餐具。\r\n\r\n報名期間：2018/05/02~2018/05/02",
    "imageUrl": "",
    "masterUnit": ["國立臺灣史前文化博物館"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://event.culture.tw/NMP/portal/Registration/C0103MAction?actId\u003d80043",
    "sourceWebPromote": "http://event.culture.tw/NMP",
    "comment": "",
    "editModifyDate": "2018/07/06 09:57:21",
    "sourceWebName": "藝文活動報名平台",
    "startDate": "2018/09/01",
    "endDate": "2019/06/30",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5c758d96d083a35404c3dc61",
    "title": "桃園市立圖書館龜山分館「愛最大」系列電影展6月份 (5場)",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/01 14:00:00",
        "location": "桃園市龜山區自強南路97號",
        "locationName": "桃園市立圖書館龜山分館",
        "onSales": "N",
        "price": "",
        "latitude": "0.0",
        "longitude": "0.0",
        "endTime": "2019/06/29 16:00:00"
      }
    ],
    "showUnit": "(不分國籍)本活動無實體展演者",
    "discountInfo": "",
    "descriptionFilterHtml": "6/01(六)被偷走的那五年(普)片長108分鐘\r\n6/08(六)丹麥女孩(輔)片長120分鐘\r\n6/15(六)以你的名字呼喚我(輔)片長132分鐘\r\n6/22(六)水底情深(輔)片長124分鐘\r\n6/29(六)月光下的藍色男孩(輔)片長111分鐘\r\n",
    "imageUrl": "",
    "masterUnit": ["桃園市立圖書館"],
    "subUnit": ["桃園市立圖書館龜山分館"],
    "supportUnit": [],
    "otherUnit": ["(指導)桃園市政府文化局"],
    "webSales": "",
    "sourceWebPromote": "",
    "comment": "桃市圖",
    "editModifyDate": "",
    "sourceWebName": "全國藝文活動資訊系統",
    "startDate": "2019/06/01",
    "endDate": "2019/06/29",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5c758d97d083a35404c3dc62",
    "title": "桃園市立圖書館龜山分館「職場養成訓練所」系列電影展暨「兒童暑假電影院」7月份 (9場)",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/07/03 14:00:00",
        "location": "桃園市龜山區自強南路97號",
        "locationName": "桃園市立圖書館龜山分館",
        "onSales": "N",
        "price": "",
        "latitude": "0.0",
        "longitude": "0.0",
        "endTime": "2019/07/31 16:00:00"
      }
    ],
    "showUnit": "(不分國籍)本活動無實體展演者",
    "discountInfo": "",
    "descriptionFilterHtml": "7/03(三)怪物的孩子(護)片長119分鐘\r\n7/06(六)高年級實習生(護)片長122分鐘\r\n7/10(三)銀魂:完結篇(劇場版)永遠的萬事屋(護)片長110分鐘\r\n7/13(六)怪獸大學(普)片長104分鐘\r\n7/17(三)無敵破壞王(護)片長101分鐘\r\n7/20(六)穿著PRADA的惡魔(普)片長109分鐘\r\n7/24(三)泰山(普)片長88分鐘\r\n7/27(六)救救蔡英文(普)片長134分鐘\r\n7/31(三)米奇、唐老鴨、高飛三劍客(普)片長64分鐘\r\n",
    "imageUrl": "",
    "masterUnit": ["桃園市立圖書館"],
    "subUnit": ["桃園市立圖書館龜山分館"],
    "supportUnit": [],
    "otherUnit": ["(指導)桃園市政府文化局"],
    "webSales": "",
    "sourceWebPromote": "",
    "comment": "桃市圖",
    "editModifyDate": "",
    "sourceWebName": "全國藝文活動資訊系統",
    "startDate": "2019/07/03",
    "endDate": "2019/07/31",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cd90ed3aaa3f054c2cc6bbf",
    "title": "【2019地球影展】台北場：守護。手護。By Your He",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/05/07 00:00:00",
        "location": "臺北市各地",
        "locationName": "北北基",
        "onSales": "N",
        "price": "",
        "latitude": null,
        "longitude": null,
        "endTime": "2019/09/16 00:00:00"
      }
    ],
    "showUnit": "",
    "discountInfo": "",
    "descriptionFilterHtml": "荒野保護協會每年透過動人的影像故事，\r\n帶領民眾走進自然、了解自然。\r\n今年台北分會以「守護。手護。」\r\n作為倡議行動的核心價值，\r\n讓我們從日常生活中與生態環境共並進，\r\n由城市作為一個起點，🌿\r\n關心周遭的自然生態與環境，\r\n進而行動關心我們的家園、守護臺灣自然棲地。\r\n歡迎停下腳步、靜下心，進入攝影師的眼，\r\n看見不一樣的地球，🌏\r\n打開自然的感官來體驗人與土地的關係\r\n　\r\n　\r\n🌿2019地球影展片單🌿\r\n\r\n《解密穿山甲》《日本再生-尋找新能源典範》\r\n《魚線的盡頭》《給親愛的孩子》\r\n《怒海控塑》《和禾歲記》《海鯖迴家》\r\n《迷海龜途》《只有一個》《月光海岸》\r\n《鳥之湯》《還島》《保島》《絕處逢生》\r\n　　\r\n影展場次一覽：\r\nhttps://www.sow.org.tw/civicrm/event/info?id\u003d6894\u0026reset\u003d1",
    "imageUrl": "http://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D13/E143/F268/cfda95e4-088e-48ff-a975-a60671760bf5.JPG",
    "masterUnit": ["荒野保護協會台北分會"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "",
    "sourceWebPromote": "https://www.sow.org.tw/civicrm/event/info?id\u003d6894\u0026reset\u003d1",
    "comment": "",
    "editModifyDate": "2019/05/14 17:28:29",
    "sourceWebName": "慌慌",
    "startDate": "2019/05/07",
    "endDate": "2019/09/16",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cdb8378d083a32cb038abfc",
    "title": "【2019地球影展】6/13、6/20、6/27場次開始報名囉！",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/19 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/20 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/21 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/22 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/23 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/24 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/25 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/26 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      }
    ],
    "showUnit": "國立臺灣圖書館",
    "discountInfo": "",
    "descriptionFilterHtml": "本次影展活動邀請到荒野保護協會至本館，為讀者導賞3部與海洋生態相關的電影，影片資訊如下，歡迎讀者踴躍報名參加！ 1.06/13(四)魚線的盡頭 地點：本館1F簡報室 報到時間：13:30-14:00 放映時間：14:00-16:00 報名連結：https://www.sow.org.tw/civicrm/event/register?id\u003d8572\u0026reset\u003d1 2.06/20(四)海鯖迴家 地點：本館1F簡報室 報到時間：13:30-14:00 放映時間：14:00-16:00 報名連結：https://www.sow.org.tw/civicrm/event/register?id\u003d8565\u0026reset\u003d1 3.06/27(四)日本再生-尋找新能源典範 地點：本館1F簡報室 報到時間：13:30-14:00 放映時間：14:00-16:00 報名連結：https://www.sow.org.tw/civicrm/event/register?id\u003d8581\u0026reset\u003d1 註：此3場次為合作影展，將取代本館6/13、6/20、6/27週四例行影展，僅放映1場，請各位讀者留意! 若有任何問題，歡迎撥打以下電話： 02-2926-6888分機3519 呂小姐",
    "imageUrl": "",
    "masterUnit": [],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "",
    "sourceWebPromote": "http://www.ntl.edu.tw/ct.asp?xItem\u003d67788\u0026ctNode\u003d1677\u0026mp\u003d1",
    "comment": "",
    "editModifyDate": "2019/05/02 00:00:00",
    "sourceWebName": "",
    "startDate": "2019/06/12",
    "endDate": "2019/06/26",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cdb837ad083a32cb038ac0a",
    "title": "108年6月電影聽賞「歡迎來到美國」",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/22 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      }
    ],
    "showUnit": "國立臺灣圖書館",
    "discountInfo": "",
    "descriptionFilterHtml": "片長：98分鐘 (普) 時間：6/22（六）14：00-17：00 地點：1F簡報室 導賞人：黃英雄老師 (臺灣編劇藝術協會理事長) 電影簡介： 印度北方有個小村吉瓦埔，村民特別嚮往美國，每當有來自美國的家書寄達時，全村的人都會感到欣喜若狂。拉瑪雖不懂美國有什麼好，但父母只要一收到哥哥烏迪從美國寄來的信，就會非常開心。某天，他旅居美國的哥哥突然斷了音訊，為不讓母親擔心，在好友拉魯鼎力支持下，出發尋找哥哥烏迪，希望兄弟倆能一同攜手回家。 笑淚交織的劇情，不僅獲得權威的\"綜藝報\"好評「細微處比寶萊塢電影更大氣」，更一舉奪下日舞影展觀眾票選最佳影片，以及棕櫚泉國際影展評審特別獎、開羅國際影展影評人費比西獎，成為近來最會得獎的印度電影。 *1F簡報室座位計有75席，放映前30分鐘開放入座，視障者優先入場，額滿為止*",
    "imageUrl": "",
    "masterUnit": [],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "",
    "sourceWebPromote": "http://www.ntl.edu.tw/ct.asp?xItem\u003d67898\u0026ctNode\u003d1677\u0026mp\u003d1",
    "comment": "",
    "editModifyDate": "2019/05/10 00:00:00",
    "sourceWebName": "",
    "startDate": "2019/06/22",
    "endDate": "2019/06/22",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf7d083a32cb038ae69",
    "title": "【府中15】紀錄片放映院《頂尖高手》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/29 16:30:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteTELCkXiTYTsw",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/06/14 18:23:45",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/29",
    "endDate": "2019/06/29",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf7d083a32cb038ae6b",
    "title": "【府中15】紀錄片放映院《世紀包浩斯》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/19 19:00:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteQn5DIzzad6fw",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/06/14 18:23:27",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/19",
    "endDate": "2019/06/19",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf7d083a32cb038ae6c",
    "title": "【府中15】紀錄片放映院《絕美之城》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/20 18:30:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteSMVPxkrmZfDw",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/06/13 18:11:37",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/20",
    "endDate": "2019/06/20",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf7d083a32cb038ae6d",
    "title": "【府中15】紀錄片放映院《揚子江風雲》 [數位修復版]",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/22 19:00:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteTxBKcqUKYW%2bw",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/06/13 18:07:32",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/22",
    "endDate": "2019/06/22",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf8d083a32cb038ae6e",
    "title": "【府中15】紀錄片放映院《預見未來：芬蘭建築大師沙里寧》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/28 19:00:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteSLrOJxMXJ5Dg",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/06/13 18:06:05",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/15",
    "endDate": "2019/06/28",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf8d083a32cb038ae6f",
    "title": "【府中15】紀錄片放映院《河北臺北》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/25 19:00:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteRCrsEqNIBAzw",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/06/13 18:02:56",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/16",
    "endDate": "2019/06/25",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf8d083a32cb038ae70",
    "title": "【府中15】紀錄片放映院《大同》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/27 19:00:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteQxAsXsSrx86w",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/05/23 16:29:22",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/16",
    "endDate": "2019/06/27",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf8d083a32cb038ae72",
    "title": "【府中15】紀錄片放映院《西城童話》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/18 18:50:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      },
      {
        "time": "2019/06/23 18:50:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteQdh2Q08oIBMQ",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/05/22 18:03:25",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/18",
    "endDate": "2019/06/23",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf8d083a32cb038ae73",
    "title": "【府中15】紀錄片放映院《公路之王》[數位修復版]",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/23 13:20:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteTjPQstWqximg",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/05/22 18:02:34",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/23",
    "endDate": "2019/06/23",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf8d083a32cb038ae74",
    "title": "【府中15】紀錄片放映院《老西門》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/23 17:00:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteTCua50%2fwUyy",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/05/22 18:02:00",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/23",
    "endDate": "2019/06/23",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf8d083a32cb038ae75",
    "title": "【府中15】紀錄片放映院《美國朋友》[數位修復版]",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/29 18:50:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteR9OaZvVqmo4w",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/05/22 17:59:21",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/29",
    "endDate": "2019/06/29",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf9d083a32cb038ae76",
    "title": "【府中15】紀錄片放映院《銀翼殺手》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/30 13:30:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteSHC%2bJ%2fxsiNFw",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/05/22 17:37:48",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/30",
    "endDate": "2019/06/30",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf9d083a32cb038ae77",
    "title": "【府中15】紀錄片放映院《銀翼殺手 2049》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/30 16:40:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteTHbyv8WtKvK",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/05/22 17:32:44",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/30",
    "endDate": "2019/06/30",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce2ddf9d083a32cb038ae78",
    "title": "【府中15】紀錄片放映院《築之夢》",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/30 20:00:00",
        "location": "新北市板橋區府中路15號B1",
        "locationName": "府中15新北市紀錄片放映院",
        "onSales": "Y",
        "price": "20",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["新北市政府 承辦：新北市政府文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteREQ5KCzFE7Xw",
    "sourceWebPromote": "http://www.fuzhong15.ntpc.gov.tw/films/",
    "comment": "",
    "editModifyDate": "2019/05/22 17:25:08",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/30",
    "endDate": "2019/06/30",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5ce58102d083a32cb038af5b",
    "title": "《安東尼與克莉奧佩特拉》英國國家劇院現場第九季",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/23 18:00:00",
        "location": "上映時間以各上映影城公告為主",
        "locationName": "威秀影城",
        "onSales": "Y",
        "price": "600",
        "latitude": null,
        "longitude": null,
        "endTime": ""
      }
    ],
    "showUnit": "",
    "discountInfo": "詳細折扣內容，請點選本節目各場次",
    "descriptionFilterHtml": "",
    "imageUrl": "",
    "masterUnit": ["威秀影城"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "http://www.artsticket.com.tw/CKSCC2005/Product/Product00/ProductsDetailsPage.aspx?ProductID\u003drotyiUrPteS%2furmmC85Yfg",
    "sourceWebPromote": "",
    "comment": "",
    "editModifyDate": "",
    "sourceWebName": "兩廳院售票網",
    "startDate": "2019/06/23",
    "endDate": "2019/06/23",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cec96c8d083a32cb038b1f6",
    "title": "資料中心108年6月精選影片:藝術解密",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/01 09:00:00",
        "location": "403  臺中市西區五權西路一段2號",
        "locationName": "多媒體區Multimedia area",
        "onSales": "N",
        "price": "",
        "latitude": "24.1411826",
        "longitude": "120.6633086",
        "endTime": "2019/06/30 09:00:00"
      }
    ],
    "showUnit": "",
    "discountInfo": "",
    "descriptionFilterHtml": "片名：藝術解密\r\n索書號：DVD 906.8 4223 V.1-V.4\r\n片長：4張數位影音光碟約208分(DVD, 單片約54分鐘)\r\n觀賞地點：三樓資料中心多媒體區(請由大廳入口左側搭電梯或走旋轉梯上3F)\r\n\r\n內容大綱：\r\n\r\nContents: Disc1, 巴黎市立現代美術館\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;※未完成的舞蹈(舞蹈系列)－馬諦斯\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;※運 動 (漆版畫)－尚\u0026bull;杜南\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp; Disc2, 坎佩爾美術館\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp; ※ 孔利田園 (蝕刻畫)－尚\u0026bull;慕藍\u0026nbsp;\u0026nbsp;\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp; ※ 鵝(壁飾畫) - 高更\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp; Disc3, 里耳美術館\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp; ※ 希洛德之宴(平版浮雕)－唐那提羅\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp; ※ 老婦們(時光)－哥雅\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp; Disc4, 法柏爾美術館\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp; ※ 維納斯和阿多尼斯－普桑\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\r\n\r\n\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp;\u0026nbsp; ※ 顫抖的女孩(冬天)－烏東\r\n\r\n人類開始之際，文化也隨之誕生。數千年前的壁畫至今日的科技作品，人類不斷地創造文化，也留下難以數計的珍貴遺產，陳列於世界各大博物館，供後人欣賞藝術家的創作精髓。\r\n\r\n《藝術解密》為您深究被人遺忘的一些作品，或繪畫、或雕刻，追溯創作來源及作者的創作理念與過程，為您解開這些名作背後真正的創作意涵及不解之謎！\r\n\r\n\r\n〈以上資料摘錄自DVD片封面〉\r\n本館資料中心典藏豐富的圖書、期刊、影音資料，歡迎蒞臨使用！\r\n\r\n報名期間：2019/05/20~2019/05/20",
    "imageUrl": "",
    "masterUnit": ["國立臺灣美術館"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "https://event.culture.tw/NTMOFA/portal/Registration/C0103MAction?actId\u003d90069",
    "sourceWebPromote": "https://event.culture.tw/NTMOFA",
    "comment": "",
    "editModifyDate": "",
    "sourceWebName": "藝文活動報名平台",
    "startDate": "2019/06/01",
    "endDate": "2019/06/30",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cedf937d083a32cb038b293",
    "title": "108年6月視聽區影片欣賞",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/19 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/20 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/21 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/22 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/23 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/24 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/25 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/26 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/27 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/28 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      },
      {
        "time": "2019/06/29 12:00:00",
        "location": "新北市中和區中安街八十五號",
        "locationName": "國立臺灣圖書館",
        "onSales": "N",
        "price": "",
        "latitude": "121.51229",
        "longitude": "25.00161",
        "endTime": ""
      }
    ],
    "showUnit": "國立臺灣圖書館",
    "discountInfo": "",
    "descriptionFilterHtml": "專題電影院：《碧海藍天 The Big Blue》 播放地點：B1國際會議廳 播放時間：14：00起 時間 片名 片長 06/23(日) 當我身處那片湛藍, 總會找不到浮出水面的理由。賈克與恩佐是一起長大的好友，同樣都對潛水與海洋充滿熱愛，一向好勝的恩佐總是把賈克當做敵手。長大後，恩佐重遇賈克，兩人相約一同參加潛水極限比賽，隨著比賽的進行，賈克一次次突破極限來到深海，每次回來都更加沈溺於深海的幽藍中。在一場最後的對決中，賈克受了重傷卻仍發了瘋的獨自潛入海底，在深海裡，他看見了一隻海豚……。 169分 (輔) [英] 主題電影院：《與海共存》 影片播放地點：1樓簡報室 播放場次： ※【宣告黎明的露之歌】播放場次為2場，第1場 14:00起播放、第2場16:30起播放。 ※【2019地球影展】影片僅播放一場，13:30-14:00開放報到，活動時間為14:00-16:00。(含影片播放與導賞，共2小時) 時間 片名 片長 06/06(四) 宣告黎明的露之歌 Lu over the wall 日無是有美人魚傳說的一個漁港。初中生海在父母離異後，跟隨父親來到日無。 海因為父母離異而鬱鬱寡歡，直到他發現自己的音樂竟能引起人魚女孩露的共鳴。露對海說：「我要和大家當好朋友。」但當人們發現傳說中的人魚現身，紛紛盤算著利益關係，廣受歡迎的露，究竟是找到更多朋友，或只是被當成珍奇異獸的物品呢？ 111分(普) [日] 06/13(四) 【2019地球影展】魚線的盡頭 本片由歐美各地之民間組織及基金會贊助拍攝，耗時兩年講述海洋漁業資源過度捕撈的現象。我們可以看見全球人類對魚類的鍾愛所帶來的影響。如果大家未曾想到海洋出現的警訊，進而採取行動，漁業產業的末日則將為期不遠，許多仰賴海產為生的地區也將會面臨到嚴重的饑荒問題。 83分(普) [英] 紀錄片 06/20(四) 【2019地球影展】海鯖迴家 海鯖是海裡的鯖魚，黑潮的湧昇讓鯖魚如同恩賜般，每年來到南方澳。 曾經，這裡被稱為「鯖魚的故鄉」，但近年來魚兒越來越少，究竟發生了什麼事?我們是否慢慢消耗殆盡這個黑潮的恩賜? 2017年，有12個人用獨木舟渡過黑潮的湧浪，記憶每一隻為人類被抓上岸的鯖魚。這不僅是一個獨木舟的冒險計畫，而是一個為了鯖魚划行的旅程，因為海裡的鯖魚就如同我們，都接受著大海的養育長大，都是大海的兄弟與子女。幫助牠們，其實就是幫助自己。 83分(普) [中] 紀錄片 06/27(四) 【2019地球影展】日本再生-尋找新能源典範 帶領福島災民打官司的河合弘之律師，經常被問到「不用核電，又要保持電力穩定，要用甚麼電呢？」、「再生能源又貴又不穩定，大量使用不會造成缺電嗎？」。他與日本再生能源政策專家飯田哲也先生，花了一年半的時間，拜訪了7個國家與地區，了解他們如何解決能源需求的問題，製作完成這部「日本再生－尋找新能源典範」影片。 90分(普) [英] 紀錄片 ( 護 )：未滿6歲之兒童不得觀賞，6歲以上12歲未滿之兒童須父母、師長或成年親友陪伴觀賞。 ( 輔 )：未滿12歲之兒童不得觀賞，提醒您依規定分級欣賞影片。 本館保有上述使用規定解釋權，若有未盡事宜，依現場公告為準。 若有疑問，請撥打02-29266888 #3519 呂小姐",
    "imageUrl": "",
    "masterUnit": [],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "",
    "sourceWebPromote": "http://www.ntl.edu.tw/ct.asp?xItem\u003d67994\u0026ctNode\u003d1677\u0026mp\u003d1",
    "comment": "",
    "editModifyDate": "2019/05/31 00:00:00",
    "sourceWebName": "",
    "startDate": "2019/06/12",
    "endDate": "2019/06/29",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cef87e5aaa3b03506344024",
    "title": "【桃拾露天電影院】海底總動員2：多莉去哪兒 ",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/29 19:30:00",
        "location": "桃園市八德區桃拾街",
        "locationName": "桃拾生活廣場 The Tao\u0027s Plaza",
        "onSales": "N",
        "price": "",
        "latitude": "24.955171",
        "longitude": "121.297679",
        "endTime": "2019/06/29 21:30:00"
      }
    ],
    "showUnit": "桃拾生活廣場 The Tao\u0027s Plaza",
    "discountInfo": "",
    "descriptionFilterHtml": "2019年，再度進入夏日，桃拾露天電影院即將展開序幕。\r\n\r\n夏夜晚風吹拂，月亮高掛星空，為了讓大夥兒的夏夜不只是待在冷氣房內，還能出來活動連絡情誼。桃拾生活廣場內有星巴克、陶板屋、Nu Pasta、金和刀切麵食工坊、佰元鍋、樂客牛排等餐廳供您選擇，廣場對面也有7-11，在電影開演前，不妨考慮在此用餐，讓我們與親朋好友享樂的時光更加充實，接下來帶著自備的墊子或是板凳，坐下來欣賞電影，度過一個愉快的夜晚。\r\n\r\n\r\n●放映電影：海底總動員2：多莉去哪兒 Finding Dory\r\n●放映時間：2019/06/29 (六) 19:30 \r\n●放映地點：桃拾生活廣場 (桃園市八德區桃拾街) \r\n●入場方式：免費觀賞，需自行攜帶板凳or席地坐 \r\n●停車資訊：八德金和路普客24停車場 \r\n●備註事項：當天如遇天候不佳或不可抗力之因素，活動單位保有變更取消之權利",
    "imageUrl": "http://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D30/E165/F441/06939fd0-fa1c-4489-bfb7-46adb7b1da02.png",
    "masterUnit": ["桃拾生活廣場 The Tao\u0027s Plaza"],
    "subUnit": ["桃大機構"],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "",
    "sourceWebPromote": "",
    "comment": "",
    "editModifyDate": "2019/06/05 15:33:10",
    "sourceWebName": "桃拾生活廣場 The Tao\u0027s Plaza",
    "startDate": "2019/06/29",
    "endDate": "2019/06/29",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cef91caaaa3b03506344025",
    "title": "【桃拾露天電影院】超人特攻隊2",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/07/13 19:30:00",
        "location": "桃園市八德區桃拾街",
        "locationName": "桃拾生活廣場 The Tao\u0027s Plaza",
        "onSales": "N",
        "price": "",
        "latitude": "24.955171",
        "longitude": "121.297679",
        "endTime": "2019/07/13 21:30:00"
      }
    ],
    "showUnit": "桃拾生活廣場 The Tao\u0027s Plaza",
    "discountInfo": "",
    "descriptionFilterHtml": "2019年，再度進入夏日，桃拾露天電影院即將展開序幕。\r\n\r\n夏夜晚風吹拂，月亮高掛星空，為了讓大夥兒的夏夜不只是待在冷氣房內，還能出來活動連絡情誼。桃拾生活廣場內有星巴克、陶板屋、Nu Pasta、金和刀切麵食工坊、佰元鍋、樂客牛排等餐廳供您選擇，廣場對面也有7-11，在電影開演前，不妨考慮在此用餐，讓我們與親朋好友享樂的時光更加充實，接下來帶著自備的墊子或是板凳，坐下來欣賞電影，度過一個愉快的夜晚。\r\n\r\n\r\n●放映電影：超人特攻隊2 Incredibles 2\r\n●放映時間：2019/07/13 (六) 19:30 \r\n●放映地點：桃拾生活廣場 (桃園市八德區桃拾街) \r\n●入場方式：免費觀賞，需自行攜帶板凳or席地坐 \r\n●停車資訊：八德金和路普客24停車場 \r\n●備註事項：當天如遇天候不佳或不可抗力之因素，活動單位保有變更取消之權利",
    "imageUrl": "http://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D30/E162/F8/ed39c4bb-60fb-4937-8d5f-793fdd783b88.png",
    "masterUnit": ["桃拾生活廣場 The Tao\u0027s Plaza"],
    "subUnit": ["桃大機構"],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "",
    "sourceWebPromote": "",
    "comment": "",
    "editModifyDate": "2019/06/05 15:32:35",
    "sourceWebName": "桃拾生活廣場 The Tao\u0027s Plaza",
    "startDate": "2019/07/13",
    "endDate": "2019/07/13",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cef94ecaaa3b03506344026",
    "title": "【桃拾露天電影院】神偷奶爸3",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/07/27 19:30:00",
        "location": "桃園市八德區桃拾街",
        "locationName": "桃拾生活廣場 The Tao\u0027s Plaza",
        "onSales": "N",
        "price": "",
        "latitude": "24.955171",
        "longitude": "121.297679",
        "endTime": "2019/07/27 21:30:00"
      }
    ],
    "showUnit": "桃拾生活廣場 The Tao\u0027s Plaza",
    "discountInfo": "",
    "descriptionFilterHtml": "2019年，再度進入夏日，桃拾露天電影院即將展開序幕。\r\n\r\n夏夜晚風吹拂，月亮高掛星空，為了讓大夥兒的夏夜不只是待在冷氣房內，還能出來活動連絡情誼。桃拾生活廣場內有星巴克、陶板屋、Nu Pasta、金和刀切麵食工坊、佰元鍋、樂客牛排等餐廳供您選擇，廣場對面也有7-11，在電影開演前，不妨考慮在此用餐，讓我們與親朋好友享樂的時光更加充實，接下來帶著自備的墊子或是板凳，坐下來欣賞電影，度過一個愉快的夜晚。\r\n\r\n\r\n●放映電影：神偷奶爸3 Despicable Me 3 \r\n●放映時間：2019/07/27 (六) 19:30 \r\n●放映地點：桃拾生活廣場 (桃園市八德區桃拾街) \r\n●入場方式：免費觀賞，需自行攜帶板凳or席地坐 \r\n●停車資訊：八德金和路普客24停車場 \r\n●備註事項：當天如遇天候不佳或不可抗力之因素，活動單位保有變更取消之權利",
    "imageUrl": "http://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D31/E103/F971/aa6d3888-a29e-4e33-bf00-ccceba0cad26.png",
    "masterUnit": ["桃拾生活廣場 The Tao\u0027s Plaza"],
    "subUnit": ["桃大機構"],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "",
    "sourceWebPromote": "",
    "comment": "",
    "editModifyDate": "2019/06/05 15:32:10",
    "sourceWebName": "桃拾生活廣場 The Tao\u0027s Plaza",
    "startDate": "2019/07/27",
    "endDate": "2019/07/27",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cef958eaaa3b03506344027",
    "title": "【桃拾露天電影院】 無敵破壞王2：網路大暴走",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/08/17 19:30:00",
        "location": "桃園市八德區桃拾街",
        "locationName": "桃拾生活廣場 The Tao\u0027s Plaza",
        "onSales": "N",
        "price": "",
        "latitude": "24.955171",
        "longitude": "121.297679",
        "endTime": "2019/08/17 21:30:00"
      }
    ],
    "showUnit": "桃拾生活廣場 The Tao\u0027s Plaza",
    "discountInfo": "",
    "descriptionFilterHtml": "2019年，再度進入夏日，桃拾露天電影院即將展開序幕。\r\n\r\n夏夜晚風吹拂，月亮高掛星空，為了讓大夥兒的夏夜不只是待在冷氣房內，還能出來活動連絡情誼。桃拾生活廣場內有星巴克、陶板屋、Nu Pasta、金和刀切麵食工坊、佰元鍋、樂客牛排等餐廳供您選擇，廣場對面也有7-11，在電影開演前，不妨考慮在此用餐，讓我們與親朋好友享樂的時光更加充實，接下來帶著自備的墊子或是板凳，坐下來欣賞電影，度過一個愉快的夜晚。\r\n\r\n\r\n●放映電影：無敵破壞王2：網路大暴走Ralph Breaks the Internet: Wreck-It Ralph 2\r\n●放映時間：2019/08/17 (六) 19:30 \r\n●放映地點：桃拾生活廣場 (桃園市八德區桃拾街) \r\n●入場方式：免費觀賞，需自行攜帶板凳or席地坐 \r\n●停車資訊：八德金和路普客24停車場 \r\n●備註事項：當天如遇天候不佳或不可抗力之因素，活動單位保有變更取消之權利",
    "imageUrl": "http://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D30/E163/F636/2e9def6e-c71b-48ad-8578-17f6424c09d4.png",
    "masterUnit": ["桃拾生活廣場 The Tao\u0027s Plaza"],
    "subUnit": ["桃大機構"],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "",
    "sourceWebPromote": "",
    "comment": "",
    "editModifyDate": "2019/06/05 15:31:37",
    "sourceWebName": "桃拾生活廣場 The Tao\u0027s Plaza",
    "startDate": "2019/08/17",
    "endDate": "2019/08/17",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cf81369d083a347acedce93",
    "title": "6月份文化電影欣賞",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/06/01 09:30:00",
        "location": "花蓮縣花蓮市文復路六號",
        "locationName": "花蓮縣文化局",
        "onSales": "N",
        "price": "",
        "latitude": "0.0",
        "longitude": "0.0",
        "endTime": "2019/06/30 11:30:00"
      }
    ],
    "showUnit": "(中華民國)花蓮縣文化局",
    "discountInfo": "",
    "descriptionFilterHtml": "6/01(六)姊妹、6/02(日)BJ單身日記、6/08(六)少年Pi的奇幻漂流、6/09(日)傲慢與偏見、6/15(六)美味關係、6/16(日)丹麥女孩、6/22(六)岸邊之旅、6/23(日)生命中的美好缺憾、6/29(六)偷書賊、6/30(日)我出去一下。",
    "imageUrl": "",
    "masterUnit": ["花蓮縣文化局"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "",
    "sourceWebPromote": "",
    "comment": "",
    "editModifyDate": "",
    "sourceWebName": "全國藝文活動資訊系統",
    "startDate": "2019/06/01",
    "endDate": "2019/06/30",
    "hitRate": 0
  },
  {
    "version": "1.4",
    "UID": "5cff98e9d083a347acedd060",
    "title": "第九屆野望國際⾃然影展",
    "category": "8",
    "showInfo": [
      {
        "time": "2019/07/06 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/07/06 10:30:00"
      },
      {
        "time": "2019/07/06 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/07/06 14:00:00"
      },
      {
        "time": "2019/07/21 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/07/21 10:30:00"
      },
      {
        "time": "2019/07/21 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/07/21 14:00:00"
      },
      {
        "time": "2019/07/27 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/07/27 10:30:00"
      },
      {
        "time": "2019/07/27 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/07/27 14:00:00"
      },
      {
        "time": "2019/08/03 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/03 10:30:00"
      },
      {
        "time": "2019/08/03 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/03 14:00:00"
      },
      {
        "time": "2019/08/10 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/10 10:30:00"
      },
      {
        "time": "2019/08/10 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/10 14:00:00"
      },
      {
        "time": "2019/08/11 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/11 10:30:00"
      },
      {
        "time": "2019/08/11 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/11 14:00:00"
      },
      {
        "time": "2019/08/17 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/17 10:30:00"
      },
      {
        "time": "2019/08/17 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/17 14:00:00"
      },
      {
        "time": "2019/08/18 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/18 10:30:00"
      },
      {
        "time": "2019/08/18 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/18 14:00:00"
      },
      {
        "time": "2019/08/24 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/24 10:30:00"
      },
      {
        "time": "2019/08/24 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/24 14:00:00"
      },
      {
        "time": "2019/08/25 10:30:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/25 10:30:00"
      },
      {
        "time": "2019/08/25 14:00:00",
        "location": "100  臺北市中正區襄陽路25號 (臺博館斜對面)",
        "locationName": "國立臺灣博物館-土銀展示館",
        "onSales": "N",
        "price": "",
        "latitude": "25.042754",
        "longitude": "121.515034",
        "endTime": "2019/08/25 14:00:00"
      }
    ],
    "showUnit": "",
    "discountInfo": "",
    "descriptionFilterHtml": "1992 年國際訂定的「⽣物多樣性公約」，到2020年時，將是檢視過去，並展望未來十年的重要階段。為了讓在台灣的我們對⽣物多樣性更多的認知，第九屆野望影展藉由最新、最優質的⽣態紀錄⽚，針對「遺傳多樣性」、「物種多樣性」和「⽣態系多樣性」三個對於生態環境最重要的概念，作為選片的主軸。我們都知道，威脅⽣物多樣性的主要因素，包括：棲地破壞、土地過度利用、氣候變遷、環境污染；近年來，外來種⼊侵問題，也成為大家擔憂。這些點點滴滴，都在提醒著我們，刻不容緩地減緩破壞的速度，才能及時挽救我們的地球！\r\n（按片名可以看到預告喔！）\r\n\r\n\r\n\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t7/6(六)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t極限巔峰安地斯\r\n\t\t\tMountain:\r\n\t\t\tLife at the Extreme\r\n\t\t\t– Andes\r\n\t\t\t(60分鐘, 英國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t \r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t北極熊流亡記\r\n\t\t\tQueen without Land\r\n\t\t\t(70分鐘, 挪威)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t美麗的北極熊媽媽，帶著兩頭⼩熊在酷寒的北極地區生活。面對全球暖化、氣候變遷，冰棚快速融化崩裂，極地生物多樣性的瓦解；北極熊一家三口能夠幸運的熬過這個危機重重的冬日暴風雪嗎？\r\n\r\n\t\t\t映後座談　吳海音副教授\r\n\t\t\t國立東華大學自然資源與環境學系\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t7/21(日)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t宇宙奇⽯：呼吸\r\n\t\t\tOne Strange Rock\r\n\t\t\t(60分鐘, 美國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t \r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t龐然⼤物螞蟻⼭\r\n\t\t\tAttenborough\u0027s\r\n\t\t\tAnt Mountain\r\n\t\t\t(51分鐘, 奧地利)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t年輕蟻后如何藉由其他種螞蟻，幫助自己登上大位？一起看看資深生態學家大衛艾登堡爵士（Sir David Attenborough)的物種多樣性大師班吧！\r\n\r\n\t\t\t映後座談　講師邀請中！\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t7/27(六)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t茱蒂丹契：愛樹成癡\r\n\t\t\tJudi Dench:\r\n\t\t\tMy Passion for Trees\r\n\t\t\t(58分鐘, 英國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t \r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t與鷹偕⾏ \r\n\t\t\tH is for Hawk:\r\n\t\t\tA New Chapter　\r\n\t\t\t(60分鐘, 英國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t2014 年海倫麥克唐納 (Helen MacDonald)出版與蒼鷹梅寶的故事 H is for Hawk《鷹與心的追尋》，被世界文壇譽為超越《老人與海》的當代經典。 後來，蒼鷹梅寶染病離世，8年後的海倫，決定再次讓蒼鷹重返她的生活\r\n\r\n\t\t\t主持人 王誠之秘書長\r\n\t\t\t野望自然傳播學社秘書長\r\n\r\n\t\t\t與談人 林思民教授\r\n\t\t\t國立師範大學生命科學專業學院\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t8/3(六)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t地球新荒野：森林\r\n\t\t\tEarth: A New Wild - Forest\r\n\t\t\t(55分鐘, 英國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t \r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t藍色星球II：共同的海洋\r\n\t\t\tBlue Planet II - One Ocean\r\n\t\t\t(60分鐘, 英國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t從溫暖的熱帶水域到寒冷的極區，擦亮你的雙眼，準備好了嗎！前所未見的海洋生物行為，即將衝擊你的感官與認知！\r\n\r\n\t\t\t映後座談  顏寧策展人\r\n\t\t\t野望影展策展人\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t8/10(六)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t野性愛爾蘭\r\n\t\t\tWild Ireland:\r\n\t\t\tThe Edge of the World\r\n\t\t\t(60分鐘, 愛爾蘭)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t \r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t溫柔巨⼈⾧頸⿅\r\n\t\t\tGiraffes: Africa\u0027s\r\n\t\t\tGentle Giants\r\n\t\t\t(60分鐘, 英國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t來自澳洲的朱利安博士在烏干達採集長頸鹿族群的DNA 樣本，藉此重建物種分類系統，油田開發危及長頸鹿們的安危，朱利安和野生動保組織能夠成功護送牠們到更安全的地方嗎？\r\n\r\n\t\t\t映後座談　吳海音副教授\r\n\t\t\t國立東華大學自然資源與環境學系\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t8/11 (日)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t剛果家園\r\n\t\t\t　My Congo　\r\n\t\t\t(60分鐘, 英國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t \r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t猩際戰⼠崛起\r\n\t\t\tRise of the Warrior Apes\r\n\t\t\t(87分鐘, 英國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t黑猩猩像人類一樣對族群成員有手足情誼，卻也像人一樣對資源的掠取不知節制，這個持續長大的黑猩猩族群能繼續維繫下去嗎？\r\n\r\n\t\t\t映後座談　張仕緯副研究員\r\n\t\t\t特有生物研究保育中心\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t8/17 (六)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t海洋秘⾟：漁撈⿊數\r\n\t\t\tAn Ocean Mystery:\r\n\t\t\tThe Missing Catch\r\n\t\t\t(46分鐘, 美國)\r\n\t\t\t\r\n\t\t\t \r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t外來巨⿏成災\r\n\t\t\tRodents of Unusual Size\r\n\t\t\t(71分鐘, 美國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t強悍的路易西安納州漁民，一生中經歷過各種天災人禍，他們近年最大的浩劫，是來自南美洲的海狸鼠，瘋狂地破壞他們的家園。磨刀霍霍的賞金獵人和繁殖力旺盛的巨型齧齒類動物，誰會是最終的獲勝者呢?\r\n\r\n\t\t\t映後座談　鄭錫奇　博士\r\n\t\t\t特有生物研究保育中心動物組組長\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t8/18 (日)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t半島調查：盜獵⿊市\r\n\t\t\tAl Jazeera Investigates\r\n\t\t\t-The Poacher\u0027s Pipeline\r\n\t\t\t(48分鐘, 卡達)\r\n\t\t\t\r\n\t\t\t \r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t獅⼦幫規\r\n\t\t\tThe Lions Rule\r\n\t\t\t- Death in the Glade\r\n\t\t\t(50分鐘, 奧地利)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t非洲坦尚尼亞的盧阿哈國家公園（Ruaha National Park），狒狒和獅子世代和平相處、各獅群比鄰而居。趕在乾季前尋找水源的水牛群，此時踏入獅群們的地盤裡，原本平靜的綠洲成為戰場，而獅群間的殘酷幫規，也出現在我們的眼前。\r\n\r\n\t\t\t映後座談  林育秀助理研究員\r\n\t\t\t特有生物研究保育中心\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t8/24(六)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t魔幻挪威峽灣\r\n\t\t\tNorway\u0027s Magical Fjords\r\n\t\t\t(52分鐘, 德國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t \r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t瀕危物種影像⽅⾈\r\n\t\t\tRARE: Creatures\r\n\t\t\tof the Photo Ark\r\n\t\t\t(53分鐘, 美國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t國家地理頻道攝影師喬沙托瑞(joel Sartore)，因緣際會地開啟物種影像方舟計畫。他走遍世界各地，利用戶外攝影棚作業的方式，紀錄全世界瀕臨滅絕的稀有物種，精采呈現整個地球生物圈的物種多樣性。\r\n\r\n\t\t\t映後座談　楊正雄 助理研究員\r\n\t\t\t特有生物研究保育中心\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t8/25(日)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t10:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t生命的法則\r\n\t\t\tThe Serengeti Rules\r\n\t\t\t(84分鐘, 美國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t \r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t14:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t暴⿓真貌\r\n\t\t\tThe Real T.rex\r\n\t\t\twith Chris Packham\r\n\t\t\t(60分鐘, 英國)\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t你印象中的暴⿓是什麼樣⼦？拖著巨大的尾巴行走？高聲咆哮、聲音震耳欲聾？這是真的嗎？跟著主持⼈及很特別的特別來賓，利用現代科技，揭開暴龍的真面貌！\r\n\r\n\t\t\t映後座談　李世緯  老師\r\n\t\t\t國立海洋科技博物館\r\n\t\t\t\r\n\t\t\r\n\t\r\n\r\n\r\n \r\n\r\n關於 Wildscreen\r\n\r\nWildscreen為設立於英國Bristol的非營利性組織（Charity no. 299450），發軔於1982年於當地舉辦的Wildscreen影展，此後每兩年舉辦一次，發展成為世界最頂尖自然影展，享有「綠色奧斯卡Green Oscar」之美譽。其贊助人包括英國飛利浦親王、生態學家愛德華‧威爾森Edward O. Wilson、海洋學家施薇雅‧厄爾Dr Sylvia Earle、大衛‧艾登堡爵士Sir David Attenborough及喬治・麥葛文(George C. McGavin)等人。除影展外，Wildscreen同時經營生物網路資料庫ARKive、生態攝影展WildPhotos、生態影片歷史典藏WildFilmHistory以及國際交流Wildscreen Outreach，並且與WWF UK、IUCN等國際組織合作，進行國際生態保育傳播及推廣。\r\n\r\n \r\n\r\n關於 台灣野望自然傳播學社\r\n\r\n由一群致力於自然保育及行銷傳播的朋友組成，宗旨為「運用專業行銷傳播能力，促進台灣自然保育之公眾認知」，從事自然保育行銷傳播之規劃顧問、教育訓練、內容之製作及出版，如紀錄片、書籍、活動…等等。台灣野望自然傳播學社成立於100年3月12日，報經內政部100年5月27日台內社字第1000094669號函准予備查。\r\n\r\n報名期間：2019/06/10~2019/08/23",
    "imageUrl": "",
    "masterUnit": ["國立臺灣博物館"],
    "subUnit": [],
    "supportUnit": [],
    "otherUnit": [],
    "webSales": "https://event.culture.tw/NTM/portal/Registration/C0103MAction?actId\u003d90037",
    "sourceWebPromote": "https://event.culture.tw/NTM",
    "comment": "",
    "editModifyDate": "2019/06/12 10:03:59",
    "sourceWebName": "藝文活動報名平台",
    "startDate": "2019/07/06",
    "endDate": "2019/08/25",
    "hitRate": 0
  }
];

module.exports = {
  rawMovieList,
}